##print("Hello world")

##print("이샘","코딩","전문","학원")
##print("코당세계에","오신걸","환영합니다")
##print("안녕하세요")
##print("안녕하세요")
##print("안녕하세요")
##print("이쌤코딩학원",",,,","hhh",end="!!")
##print("이쌤코딩학원",end="!!")
##print("이쌤코딩학원",end="!!")
##print("안녕하세요\n")
##print('안녕하세요',end="")
print("안녕하세요",end='')
